### ISSUE TITLE
Bad escaping of double quotes in fields (e.g. "store" field)

### ISSUE THREAD

**Issue by liberforce** [giventofly/exportpwp#4]
Seems the header has the "store" field badly quoted. The first quote is missing.

So instead of:
```
"date","description","store",...
```

I got:
```
"date","description",store",...
```

**Comment by liberforce** [comment]
I also have some tournament "place" name that have double quotes in them, I'm not sure how they should be escaped in the generated csv:
```
Palais des congrès "Paris Est Montreuil"
```
becomes in the CSV: 
```
"Palais des congrès "Paris Est Montreuil""
```

**Comment by giventofly** [comment]
both fixed (try it please)! thanks.

**Comment by liberforce** [comment]
Thanks. The header bug is fixed, but the escaping problem remains, the generated text is the same.

Instead of:
```
"Palais des congrès "Paris Est Montreuil""
```
it should be:
```
"Palais des congrès ""Paris Est Montreuil"""
```
or:
```
"Palais des congrès \"Paris Est Montreuil\""
```

**Comment by giventofly** [comment]
Damn, sorry, my IDE added an extra " when I was making the replacer, will fix it now, could you try again?

**Comment by liberforce** [comment]
Still the same result.

**Comment by liberforce** [comment]
Sorry, my bad. In fact that text looks like a location but is inside the "store" field. So what is missing is the escaping of the "store" field.

**Comment by giventofly** [comment]
Should be working now, test please.

**Comment by liberforce** [comment]
Also not fixed, please reopen.

**Comment by giventofly** [comment]
Js seems to be right and working (with a test example), I can't do a real test because don't have that case.

But everything should be working. Feel free to do a pull request, or try to give me more info.

EDIT:
 found where to reopen the issue.

**Comment by giventofly** [comment]
Isn't it working? All the tests I did seemed to work

**Comment by liberforce** [comment]
No, still doesn't work. I still get:
```
"Palais des congrès "Paris Est Montreuil""
```

**Comment by giventofly** [comment]
Let try some debugging, below the line:
```javascript    
content += `"${date}","${description}","${location}","${eventLocation}","${lifetimepoints}","${propoints}","${multiplier}","${totalPlayers}","${eventFormat}","${place}","${roundNumber}","${result}","${opp}"\r\n`; 
```
add this:
`console.log(location,location.replace(/(")/gm,"").trim(),location.replace(/(")/gm,'\"').trim());`

And paste the new code (open+expand manually the event with the " on it) and give me the output please

**Comment by liberforce** [comment]
I tried to debug it, and figured out the replacement sequence should be `"\\"`, which makes sense, since you need to print the backslash and it is already an escapement character, so it needs o be doubled.

However, even if the output file looks correct, the import in Libreoffice Calc fails. I've then tried  escaping by doubling the double quotes, and it works fine. Merge request on the way.

**Comment by liberforce** [comment]
See PR #9 .
