### ISSUE TITLE
Suppress redundant output in fields

### ISSUE THREAD

**Issue by liberforce** [giventofly/exportpwp#5]
Field names are repeated in the output. For example, `"Format : Sealed"` could be just `"Sealed"`. You just have to split around the `:`  and trim heading space of the result.

**Comment by giventofly** [comment]
Fixed for all :) thanks

**Comment by liberforce** [comment]
I just tested, it doesn't seem fixed. Also, please don't close issues before they are confirmed as fixed.

**Comment by giventofly** [comment]
Tested here and it worked (for all fields). I didn't find where to reopen, and the code works in vacuum so let's try to debug on your side.

What browser are you using?

**Comment by giventofly** [comment]
Tested right now using the code from the page and got the correct results:
```
"date","description","store","location","points","pro points","multiplier","total event players","format","place","round number","result","opponent"
"2020-03-08","Magic Tournament","Magus","Vila Nova de Famalicão","4","-","x 1","8","Modern","6","1","Win","Jaime Azevedo"
"2020-03-08","Magic Tournament","Magus","Vila Nova de Famalicão","4","-","x 1","8","Modern","6","2","Loss","Cesar Pinto"
"2020-03-08","Magic Tournament","Magus","Vila Nova de Famalicão","4","-","x 1","8","Modern","6","3","Loss","Mario Abreu"
"2020-02-29","Magic Tournament","Magus","Vila Nova de Famalicão","5","-","x 1","25","Pioneer","19","1","Loss","Jeffery Patterson"
"2020-02-29","Magic Tournament","Magus","Vila Nova de Famalicão","5","-","x 1","25","Pioneer","19","2","Win","Gonçalo Teixeira"
"2020-02-29","Magic Tournament","Magus","Vila Nova de Famalicão","5","-","x 1","25","Pioneer","19","3","Loss","luis rodrigues"
```

**Comment by liberforce** [comment]
I gave a look to the code. You're matching the english text, which means if the website is configured in another language, it won't match. I was configured in French (também falo português se você quiser ;)). That's why I told you to split the string on the `:` character: it should be present in all languages.

**Comment by giventofly** [comment]
Never crossed my mind that the site could be served in other languages, always assumed it was english. Yeah, in that case the ":" need to be the delimiter, will pin this to when have the time to fix it.

**Comment by liberforce** [comment]
Yeah, the language selection is done using the top link at the very bottom of the page.

**Comment by giventofly** [comment]
If you have the time to do a pull request to fix using the ":" I can accept it, otherwise I will only have time tomorrow to change it

**Comment by liberforce** [comment]
I'm a total javascript noob, I'm a C/C++/Python guy, and I've fixed my exported data yesterday (been playin for 24 years but only did 14 events, mainly pre-releases), so this can completely wait until tomorrow :). I opened the issues mainly to help people that have much bigger histories.
Another advantage of putting the code in a separate file is that I'l be able to learn from the diffs ;)

**Comment by zendamacf** [comment]
I've created a pull request that replaces out the title from the HTML, instead of using the hardcoded English values.

There will definitely be a conflict with #9 because we've changed stuff on the same lines, but shouldn't be a hard one to fix up :)
